spring:
  datasource:
    url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_mdc?characterEncoding=utf8&useSSL=false
paascloud:
  aliyun:
    rocketMq:
      instanceName: paascloud-provider-mdc
      consumerGroup: CID_MDC
      producerGroup: PID_MDC