spring:
  datasource:
    url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_uac?characterEncoding=utf8&useSSL=false
paascloud:
  aliyun:
    rocketMq:
      instanceName: paascloud-provider-uac
      consumerGroup: CID_UAC
      producerGroup: PID_UAC
  auth:
    rest-pwd-url: http://dev-login.paascloud.net/resetPwd?resetPwdKey=
    active-user-url: http://dev-api.paascloud.net:7979/uac/auth/activeUser/
    refresh-token-url: http://dev-api.paascloud.net:7979/uac/oauth/token